birds/urls.py
from django.urls import path

from birds.apps import BirdsConfig
from birds.views import BirdsListView, BirdsCreateView, BirdsDetailView, \
    BirdsUpdateView, BirdsDeleteView, view_birds, ViewBirdsListView

app_name = BirdsConfig.name

urlpatterns = [
    path('', BirdsListView.as_view(), name='list'),
    path('create/', BirdsCreateView.as_view(), name='create'),
    path('view/<int:pk>/', BirdsDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BirdsUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BirdsDeleteView.as_view(), name='delete'),
    path('<int:pk>/birds/', view_birds, name='birds_view'),
    path('view_birds/', ViewBirdsListView.as_view(), name='view_birds')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('birds.urls', namespace='birds')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

birds/models.py
from django.db import models
from django.forms import DateTimeField

NULLABLE = {'blank': True, 'null': True}  # Используется, как указание - "Необязательный атрибут"


class Birds(models.Model):
    objects = None
    name = models.CharField(max_length=150, verbose_name='Название птицы')
    color_feather = models.CharField(max_length=150, verbose_name='Цвет перьев', **NULLABLE)
    image_bird = models.ImageField(upload_to='image', height_field=None, width_field=None, max_length=100, **NULLABLE)
    vision_attribute = models.BooleanField(default=False, verbose_name='Видел')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.name}'

    class Meta:
        verbose_name = 'Птица'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Птицы'  # Настройка для наименования набора объектов


class ViewBirds(models.Model):
    name = models.ForeignKey(Birds, on_delete=models.CASCADE, verbose_name='Название птицы')
    image_bird = models.ImageField(upload_to='image', height_field=None, width_field=None, max_length=100, **NULLABLE)
    number_of_views = models.IntegerField(default=0, verbose_name='количество просмотров')
    time_date_now = models.DateTimeField(**NULLABLE)

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.name}'

    class Meta:
        verbose_name = 'Видел Птицу '  # Настройка для наименования одного объекта
        verbose_name_plural = 'Видел Птиц'  # Настройка для наименования набора объектов

birds/forms.py
from django import forms

from birds.models import Birds


class StyleFormMixin:  # Данный класс создан для замешивания стилей в форму
    def __init__(self, *args, **kwargs):  # Функция, которая делает вывод карточки на экран более привлекательным
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BirdForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Birds
        fields = '__all__'

birds/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from birds.forms import BirdForm
from birds.models import Birds, ViewBirds


class BirdsListView(ListView):
    model = Birds
    template_name = 'birds/birds.html'


class BirdsCreateView(CreateView):
    model = Birds
    form_class = BirdForm
    success_url = reverse_lazy('birds:list')


class BirdsDetailView(DetailView):
    model = Birds


class BirdsUpdateView(UpdateView):
    model = Birds
    form_class = BirdForm
    success_url = reverse_lazy('birds:list')


class BirdsDeleteView(DeleteView):
    model = Birds
    fields = '__all__'
    success_url = reverse_lazy('birds:list')


def view_birds(request):
    context = {
        'object_list': Birds.objects.filter(vision_attribute=True),
    }
    return render(request, 'birds/view_birds.html', context)


class ViewBirdsListView(ListView):
    model = ViewBirds
    template_name = 'birds/view_birds.html'

birds/templates/birds/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'birds/includes/inc_birds_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>
{% block content %}
{% endblock %}
        </div>
    </div>
</div>
</body>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</html>

birds/templates/birds/birds.html
{% extends 'birds/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container text-center" xmlns="">
    <p class="lead">Добро пожаловать в мой курятник)!</p>
    <div class="col-12 mb-5">
       <a class="btn btn-outline-primary" href="{% url 'birds:create' %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Добавить птичку</a>
     {% for object in object_list %}
    <div class="row">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3 ">
                        <li><img src="{{ object.image_bird|mymedia }}" class="img-fluid"/></li>
                    </ul>
                    <a href="{% url 'birds:view' object.pk %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Описание</a>
                    <a href="{% url 'birds:delete' object.pk %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                    <a href="{% url 'birds:edit' object.pk %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Изменить</a>
                </div>
            </div>
            {% endfor %}
   {% endblock %}

birds/templates/birds/birds_confirm_delete.html
{% extends 'birds/base.html' %}

    {% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить птичку "{{ object.title }}?"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'birds:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

birds/templates/birds/birds_detail.html
{% extends 'birds/base.html' %}
{% load my_tags %}
    {% block content %}
        <div class="col-12">
            <div class="row">

                <div class="col-6">
                    <div class="card">
                      <div class="card-header">
                        <h3 class="card-title">
                          Информация о Птице
                        </h3>
                      </div>
                 <div class="card-body">
                   <table class="table">
                     <tr>
                       <td>Название</td>
                       <td>{{ object.name }}</td>
                     </tr>
                     <tr>
                       <td>Цвет крыльев</td>
                       <td>{{ object.color_feather }} </td>
                     </tr>
                     <tr>
                       <td>Фото</td>
                       <td><img src="{{ object.image_bird|mymedia }}" class="img-fluid"/></td>
                     </tr>
                   </table>
                </div>
                      <div class="card-footer"></div>
                  </div>
                  </div>
            </div>
        </div>

    {% endblock %}

birds/templates/birds/birds_form.html
{% extends 'birds/base.html' %}

    {% block content %}
<div class="col-12">

    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Редактор птичек
                    </h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                </div>
            </div>
        </div>
     </form>
  </div>

    {% endblock %}

birds/templates/birds/includes/inc_birds_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Меню</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'birds:list' %}">Птицы</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'birds:view_birds' %}">Видел их</a>
    </nav>
</div>

birds/templates/birds/view_birds.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Видел Их</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'birds/includes/inc_birds_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>
{% for object in object_list %}
    <div class="row">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
</body>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</html>